myfirstapp/apps/reddit/urls.py
from django.urls import path

from . import views

# so that when you provide {url 'name of template'} it 
app_name = 'reddit'

urlpatterns = [
    path('analytics/', views.chart, name='chart'),

    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment', views.leave_comment, name='leave_comment')
]

myfirstapp/apps/stocks/urls.py
from django.urls import path

from . import views

# adding namespace and also specifying it in the templates so that
# the template brings up the correct url path.
app_name = 'stocks'

urlpatterns = [
    
    # ex: /stocks/
    path('', views.index, name='index'),

    # ex: /stocks/5
    path('<int:question_id>/', views.detail, name='detail'),

    # ex: /stocks/5/results
    path('<int:question_id>/results/', views.results, name='results'),

    # ex: /stocks/5/vote
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myfirstapp/apps/wsb/urls.py
from . import views
from django.urls import path

# adding namespace and also specifying it in the templates so that
# the template brings up the correct url path.
app_name = 'wsb'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('create_q/', views.create_q, name='create_q'),
    path('<int:subreddit_id>/', views.detail, name='detail'),
    path('<int:subreddit_id>/leave_comment', views.leave_comment, name='leave_comment'),
    path('results/', views.results, name='results'),
    path('about_me/', views.about_me, name='about_me'),
]

myfirstapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('wsb.urls')),
    # path('stocks/', include('stocks.urls')),
    # path('reddit/', include('reddit.urls')),
    path('grappelli', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

myfirstapp/apps/reddit/models.py
import datetime
from django.db import models

from django.utils import timezone
## Используется для обьяснения для Django того что вы будете хранить в базе данных 

# Create your models here.

class Article(models.Model):
    article_title = models.CharField('article title', max_length=200)
    article_text = models.TextField('article text')
    pub_date = models.DateTimeField('date of publication')

    def __str__(self):
        return self.article_title
    
    def was_published_recently(self):
        return self.pub_date >= (timezone.now(), datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('author name', max_length=50)
    comment_text = models.CharField('commentary text', max_length=200)

    def __str__(self):
        return self.author_name
    
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

myfirstapp/apps/stocks/models.py
from django.db import models

# python's builtin standard datetime handling lib
import datetime

# django's builtin datetime awareness handling lib
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField('Question Text', max_length=500)
    pub_date = models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        condition = self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        return condition

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myfirstapp/apps/wsb/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

# python's builtin standard datetime handling lib
import datetime

# django's builtin datetime awareness handling lib
from django.utils import timezone

import random
import string
# Create your models here.


class Subreddit(models.Model):
    subreddit_name = models.CharField('Subreddit Name', max_length=255)

    # This is a Mock Choice to test the database model
    submission_title = models.CharField('Submission Title', max_length=500)
    
    regex_pattern = models.CharField('Regex Pattern', max_length=100)
    number_of_mentions = models.IntegerField(default=0)
    post_date = models.DateTimeField('Date Published', default=timezone.now)

    def __str__(self):
        return self.subreddit_name + " --> " + self.submission_title

class Comment(models.Model):
    subreddit = models.ForeignKey(Subreddit, on_delete=models.CASCADE, related_name='comment_set', default=None)
    author_name = models.CharField('author name', max_length=50)
    comment_text = models.CharField('commentary text', max_length=200)

    def __str__(self):
        return self.author_name


STATES = (
    ('', 'Choose...'),
    ('MG', 'Minas Gerais'),
    ('SP', 'Sao Paulo'),
    ('RJ', 'Rio de Janeiro')
)
# Adding ModelForms to create a Crispy Form on the HTML page.
class SubredditForm(ModelForm):
    state = forms.ChoiceField(choices=STATES, widget=forms.RadioSelect,)

    class Meta:
        model = Subreddit
        fields = ['subreddit_name', 'submission_title', 'regex_pattern']

# class CommentForm(ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['author_name']

myfirstapp/apps/wsb/forms.py
# from django import forms

# STATES = (
#     ('', 'Choose...'),
#     ('MG', 'Minas Gerais'),
#     ('SP', 'Sao Paulo'),
#     ('RJ', 'Rio de Janeiro')
# )

# class AddressForm(forms.Form):
#     email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
#     password = forms.CharField(widget=forms.PasswordInput())
#     address_1 = forms.CharField(
#         label='Address',
#         widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
#     )
#     address_2 = forms.CharField(
#         widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'})
#     )
#     city = forms.CharField()
#     state = forms.ChoiceField(choices=STATES)
#     zip_code = forms.CharField(label='Zip')
#     check_me_out = forms.BooleanField(required=False)

myfirstapp/apps/reddit/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse

from django.urls import reverse

# remember that models are tables in the database that you retrieve data from
# hence why if we want to display the data we recieved from the users we need to import
from .models import Article, Comment


# below are views specifically for stock charts
def chart(request):
    
    return render(request, 'reddit/analyser.html')



def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'reddit/list.html', {'latest_articles_list':latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Article not found")
    
    latest_comments_list = a.comment_set.order_by('-id')[:10]

    # passing in request, template, then the arguments that you would want to use in template
    return render(request, 'reddit/detail.html', {'article':a, 'latest_comments_list':latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Article not found")

    a.comment_set.create(author_name = request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('reddit:detail', args=(a.id,)))

myfirstapp/apps/stocks/views.py
# needed to respond back with a HTML template with data inside
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, response

from django.urls import reverse

# Just a basic response when sending a request to this url
from django.http import HttpResponse

from .models import Question, Choice


# defining a function that will be called out when the request is send
# to a url path
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'stocks/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'stocks/detail.html', {"question": question})

def vote(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'stocks/detail.html', {
            "question":question,
            "error_message": "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # reverse function is useful so that you don't need to hardcode
        # the URL in the view to point to.
        return HttpResponseRedirect(reverse('stocks:results', args=(question.id,)))

def results(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'stocks/results.html', {'question': question})

myfirstapp/apps/wsb/views.py
# needed to respond back with a HTML template with data inside
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, response

from django.urls import reverse

# Just a basic response when sending a request to this url
from django.http import HttpResponse

from django.views.generic import TemplateView
from matplotlib.pyplot import plot

from .models import Subreddit, Comment, SubredditForm

# django's builtin datetime awareness handling lib
from django.utils import timezone

from .reddit_analyser import plot_graph, generate_subreddit

# defining a function that will be called out when the request is send
# to a url path

# Using class it inherits methods from class VIEW which handles the linking the view into the URLs
# HTTP method dispatching and other common features
class HomeView(TemplateView):
    template_name = 'wsb/homepage.html'

    # below defining context parameters that will be passed to the url and template
    # get_context_data function will define for you a dictionary to which you can assign
    # as many parameters as you want to pass into the template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_subreddits'] = Subreddit.objects.order_by('-id')[:5]
        context['form'] = SubredditForm()
        return context

def about_me(request):
    return render(request, 'wsb/about_me.html', {})

def detail(request, subreddit_id):
    try:
        subr = Subreddit.objects.get(id=subreddit_id)
    except Subreddit.DoesNotExist:
        raise Http404("Subreddit does not exist")

    latest_comments = subr.comment_set.order_by('-id')[:10]

    return render(request, 'wsb/detail.html', {"subr": subr, "latest_comments":latest_comments,})

def leave_comment(request, subreddit_id):
    try:
        s = Subreddit.objects.get(id=subreddit_id)
    except:
        raise Http404("Subreddit not found")

    s.comment_set.create(author_name = request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('wsb:detail', args=(s.id,)))

def create_q(request):
    if request.method == "POST":
        s = Subreddit(subreddit_name=request.POST['subreddit_name'], submission_title=request.POST['submission_title'], 
                    regex_pattern=request.POST['regex_pattern'], 
                    post_date=timezone.now())
        s.save()

        if request.POST.get('generate_analysis_button', False):
            return results(request, s)
        elif request.POST.get('last_comments_button', False):
            return HttpResponseRedirect(reverse('wsb:home'))
        else:
            pass

# Below function generate analysis and displays them on the page.
def results(request, dict_things=None):
    object_dict = dict_things
    
    context={
        'object_dict':object_dict,
    }

    #generating the input from the passed data in the request dictionary
    if object_dict:
        # the first three statements below are generating input vars for the plot_graph function. So don't worry and be happy!
        regex_pattern = object_dict.regex_pattern
        subr_object, subms, sub_titles_ids = generate_subreddit(object_dict.subreddit_name)
        submission_title_selected = object_dict.submission_title

        plot_chart = plot_graph(regex_pattern, subr_object, subms, sub_titles_ids, submission_title_selected)

        context['chart'] = plot_chart[0]

        context['comments'] = plot_chart[1]

        context['comms_extracted'] = plot_chart[2]

        context['regex_pattern'] = plot_chart[3]

    

    return render(request, 'wsb/results.html', context)

myfirstapp/templates/wsb/about_me.html
{% extends 'base.html' %}

{% block title %}
About Me
{% endblock %}

{% block content %}
    <div class='row'>
        <div class="w-50 mx-auto">
            <p class='text-left'>
                Hi! Thank you for visiting my website! I really hope it was useful for your investment research! 
                <br><br>I have created this website to help investors and
                like-minded people use data from r/wallstreetbets and other subreddit groups
                to find assymetric opportunities in the stock market.
            </p>
            <p>
                <b>My skills:</b>
                <ul>
                    <li>Profiecient in Python and SQL</li>
                    <li>Familiar with HTML, CSS and JavaScript(tiny bit)</li>
                    <li>Data Analysis</li>
                        <ul>
                            <li>Pandas, Numpy, Scipy</li>
                            <li>Matplotlib and Plotly</li>
                            <li>SQL</li>
                        </ul>
                    <li>Web Development</li>
                        <ul>
                            <li>Django</li>
                            <li>HTML/CSS/JS</li>
                        </ul>
                    <li>Software Design</li>
                    <li>Networking</li>
                    <li>Agile Methodologies</li>
                </ul
            </p>
            <p>
                If you would like to get in touch with me about work opportunities
                Please send your queries <a href="mailto:nikita.izmailovv@gmail.com">here</a>
            </p>
        </div>
    </div>
{% endblock %}

myfirstapp/templates/wsb/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<h1>{{ subr.submission_title }}</h1>
{% endblock %}

{% block content %}

{% if latest_comments %}

    {% for c in latest_comments %}
        <p>
            <strong>{{c.author_name}}</strong>
            <p>{{c.comment_text}}</p>
        </p>
    {% endfor %}

{% else %}
Comments not found! Lol! Be the first one to break this streak
{% endif %}
<hr>


<form action="{% url 'wsb:leave_comment' subr.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Your Name" name="name"><br>
    <textarea name="text" required placeholder="Your Comment" cols="30" rows="10"></textarea><br>

    <button type="submit">Leave comment</button>

</form>

{% endblock %}

myfirstapp/templates/wsb/homepage.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block title %}
    r/wallstreetbets
{% endblock %}

{% block content %}
    <h2>Want to query a WSB database?</h2>
    <hr>
    <p><h4>Instructions:</h4>
    <ol>
        <li>Provide a real subreddit name. Example subreddit: <a href="https://www.reddit.com/r/wallstreetbets/">r/wallstreetbets</a></li>
        <li>Provide an actual title of the submission from the "Hot" filter (currently does not support for all submissions)</li>
        <li>Provide a tickers you want to find mentions for in comments. ex: VIAC|AMC|GME or GME for single ticker.</li>
        <li>It will take time to process all comments if the submission has more than 300 comments, so just be patient please :)</li>
    </ol>
    </p>
    <hr>
    <form action="{% url 'wsb:create_q' %}" method="POST">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                {{ form.subreddit_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                {{ form.submission_title|as_crispy_field }}
            </div>
        </div>
        {{ form.regex_pattern|as_crispy_field }}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <input type="submit" class="btn btn-primary" name="generate_analysis_button" value='Generate Analysis'>
            </div>
            <div class="form-group col-md-6 mb-0">
                <input type="submit" class="btn btn-primary" name="last_comments_button" value='Display Last 1000 Comments'>
            </div>
        </div>

    </form>
    <br>
    <h3> Last 5 queries made by users:</h3>
    <hr>
    {% if latest_subreddits %}
        {% for subr in latest_subreddits%}
            <ul class="list-group" style="list-style-type:none">    
                <div class='row'>
                    <div class="col">
                        <li class="list-group-item">
                            Subreddit: <a href="{% url 'wsb:detail' subr.id %}">{{subr.subreddit_name}}</a>
                        </li>
                    </div>
                    <div class="col">
                        <li class="list-group-item">
                            <b>Submission Title:</b>
                            <ul>
                                <li>
                                    {{subr.submission_title}}
                                </li>
                            </ul>
                            <b>Regex Pattern:</b>
                            <ul>
                                <li>
                                {{subr.regex_pattern}}
                                </li>
                            </ul>
                        </li>
                    </div>
                </div>
            </ul>
            <br>
        {% endfor %}
    {% else %}
        <h3>There are no past historical searches. Be the first one to make the query!</h3>
    {% endif %}
{% endblock %}

myfirstapp/templates/wsb/results.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {% if object_dict %}
        <h2>Results:</h2>
        <hr>
        <ul class="list-group" style="list-style-type:none">    
            <div class='row'>
                <div class="col">
                    <li class="list-group-item">
                        <b>Subreddit name:</b>
                        <ul>
                            <li>
                                {{object_dict.subreddit_name}}
                            </li>
                        </ul>
                        <b>Submission title</b>
                        <ul>
                            <li>
                                {{object_dict.submission_title}}
                            </li>
                        </ul>
                        <b>Regex pattern</b>
                        <ul>
                            <li>
                                {{object_dict.regex_pattern}}
                            </li>
                        </ul>
                    </li>
                </div>
            </div>
        </ul>
    {% else %}
        <div class='row'>
            <div class="w-50 mx-auto">
                <p>You have not provided any details about Subreddit, Subreddit's submission and Regex Pattern</p>
                <p>Please <a href="{% url 'wsb:home' %}">click here</a> to be redirected back to the home page</p>
            </div>
        </div>
    {% endif %}
    {% if chart %}
        <div class='align-self-center'>
            <img class='mx-auto d-block' src='data:image/png;base64,{{ chart }}'>
        </div>
    {% endif %}

    <div class='row'>
        <ul class="list-group" style="list-style-type:none">
            <li class="list-group-item">
                <p><b>Extraction Comepleted!</b><br>
                Total number of comments extracted: {{ comms_extracted }}<br>
                {{ comments|length }} times {{ regex_pattern }} was mentioned in the submission<br>
                </p>
            </li>
            <li class="list-group-item">
                <p><b>Below are the comments where the REGEX pattern was mentioned:</b><br>
                {% for comment in comments %}
                    {{ forloop.counter }}. {{comment}}<br>
                {% endfor %}
                </p>
            </li>
        </ul>
    </div>

{% endblock %}